steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/magical_app/my-image:tag1', '.' ]
images:
- 'gcr.io/$PROJECT_ID/magical_app/my-image:tag1'



steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/magical_app/my-image', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/magical_app/my-image']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'my-service', '--image', 'gcr.io/$PROJECT_ID/magical_app/my-image', '--region', 'northamerica-northeast2']
images:
- gcr.io/$PROJECT_ID/magical_app/my-image